### ISSUE TITLE
Presentaciones

### ISSUE THREAD

**Issue by UlisesGascon** [UlisesGascon/curso-js-web-developers-012016#1]
Hola!

Usemos este espacio para conocernos un poco más... :-)

Recordad que estos _issues_ nos permiten abrir y participar en debates, compartir recursos, plantear preguntas y muchas cosas más! 

Podemos usar [Markdown](https://guides.github.com/features/mastering-markdown/) para salirnos del texto plano y enriquecer nuestras aportaciones.

**Comment by NoemiMS** [comment]
# Buenas!!!

Soy **Noe**.

Como os conté ayer, soy maquetadora desde hace unos tres años y lo que busco con este curso es convertirme en una _Super _full-stack_ developer_ :blush:

Por si usáis twitter, aquí os dejo [mi usuario](http://twitter.com/noemedinaweb)

**Comment by PaulHilligehekken** [comment]
**Buenas Tardes**

Me llamo Paul, el _guiri_ de la clase :wink: 
Soy Holandés y vivo unos 8 años en España.

Tengo poco conocimientos con JS y estoy en la clase para aprender algo nuevo.

Aqui teneís mi [link to twitter!](https://twitter.com/Paulus5513)

Cheers!

**Comment by oscarmanzanogithub** [comment]
### Muy buenas!

Me llamo **Óscar**.

Soy diseñador _Frontend_ desde hace unos cuantos años y quiero aprender bien _JavaScript_.
Os dejo un enlace a mi [twitter](https://twitter.com/_osk_) y otro a [mi web personal](http://tonalidad.es/).

Un saludo! :wave:

**Comment by Stelair** [comment]
## Muy Buenas !!!

Mi nombre es **Juan**.

Mis inicios fueron en el lado oscuro como desarrollador de _Back-End_ con tecnologia _.NET_. Allí descubrí que mi verdadero camino estaba en el _Front_. Desde entonces me estoy formando para hacerme un hueco en este apasionante mundo.

Así que aquí estoy, intentando mejorar mis habilidades _Javascript_.

Saludos !!!

**Comment by OliverCedres** [comment]
- Buenas tardes a todos *

Me llamo **Oliver.**

Llevo en el mundo del _frontend_ muy poco, de hecho mi primer curso lo comencé el año pasado y desde entonces he seguido aprendiendo tanto por mi cuenta, como ahora con cursos como por ejemplo este de [Fictizia!](http://www.fictizia.com/formacion/curso_javascript).

Aquí os dejo mi [web personal](http://www.olivercedres.com/) ya que no soy activo en twitter. 

¡Saludos a todos!
