### ISSUE TITLE
Tonalidad - app spotify

### ISSUE THREAD

**Issue by oscarmanzanogithub** [UlisesGascon/curso-js-web-developers-012016#13]
Hola Ulises,

Acabo de volver de vacaciones y he mirado ("de reojo") la API de Spotify. En realidad no me acaba de quedar claro si es necesario loguearse (aparte de lo de la API-Key) en Spotify para poder, por ejemplo, escuchar un tema o hacer algo más allá de una búsqueda de grupos. Me pregunto lo mismo a la hora de usar la API de YouTube y otras que pudieran hacer falta. 

Por otro lado, en el ejemplo que hicimos en clase de Spotify he comprobado que no funciona en Firefox lo de dar a Intro para confirmar la búsqueda. No es que sea algo preocupante pero tengo curiosidad por saber a qué puede deberse, ya que de momento no encuentro el motivo.

En fin, a ver si consigo ir sacando tiempo para el proyecto.

Muchas gracias,
Saludos!

**Comment by UlisesGascon** [comment]
Hola @tonalidad

La API de Spotify tiene partes que funcionan sin tener que logearse y otras partes que lo requieren.

Normalmente consultar datos sobre información que es accesible no requiere de login como en el caso de artistas similares, discografías, etc...

En el caso de las canciones, en principio te permite escuchar solamente una parte de las canciones (entorno a 10-30 segundos), pero te da opciones a crear un enlace en el que poder disparar su aplicación de escritorio.

En el caso del [API de Youtube](https://www.youtube.com/yt/dev/es/api-resources.html) estoy viendo que incluso para las búsquedas ahora necesitamos estar loageados.

El ejemplo que hicimos en clase es compatible entre los distintos navegadores pero cuando subí la solución me olvide de incluir el argumento, te paso el [commit](https://github.com/Fictizia/Curso-JS-para-desarrolladores-web_ed5/commit/67ad6c9df98bebed7a09cc262738c7d3eb0ba526)

En general... cuando hablamos música las empresas intentan evitar que nos descarguemos masivamente o gratuitamente sus contenidos, por eso las APIs de este tipo son un poco enrevesadas.

Un abrazo!
